version: '3'
services:
  mysql:
    container_name: "revel_mysql"
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: revel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./docker/mysql:/docker-entrypoint-initdb.d"
  api:
    container_name: "revel_api"
    build: ./docker/api
    command: revel run api
    ports:
      - '80:9000'
    volumes:
      - "./api:/go/src/api"
    links:
      - mysql
